GRANT ALL PRIVILEGES ON DATABASE masterdiary_prod TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;
ALTER USER postgres WITH SUPERUSER;
