const sentinelService = require('../services/sentinelService');
const db = require('../models');
const { Diary, Quote, Project, AuditLog } = db;
const { logAudit } = require('../services/auditService');
// Safely load Notification model
const Notification = db.Notification || require('../models/notification')(db.sequelize, db.Sequelize.DataTypes);

const runScan = async (req, res) => {
    try {
        const { diaryId } = req.body;
        const result = await sentinelService.processDiary(diaryId, req.user.id);
        res.json(result || { message: "No leakage detected." });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

const runDeepProjectScan = async (req, res) => {
    try {
        const { projectId } = req.body;
        if (!projectId) return res.status(400).json({ error: "ProjectId is required for Deep Scan" });
        
        const result = await sentinelService.performGlobalProjectScan(projectId, req.user.id);
        
        // Log high-value audit event
        await logAudit(req.user.id, 'SENTINEL_DEEP_SCAN_COMPLETE', 'Project', projectId, {
            revenueUnlocked: result.totalRevenueUnlocked,
            diariesScanned: result.diariesScanned
        });

        res.json({ 
            message: `Deep Scan Complete. Found $${result.totalRevenueUnlocked.toLocaleString()} in unbilled work.`, 
            result 
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

const getAlerts = async (req, res) => {
    try {
        const alerts = await Notification.findAll({
            where: { 
                userId: req.user.id, 
                type: 'sentinel_alert',
                isRead: false 
            },
            order: [['createdAt', 'DESC']]
        });
        res.json(alerts);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

const getHistory = async (req, res) => {
    try {
        const history = await Notification.findAll({
            where: { 
                userId: req.user.id, 
                type: 'sentinel_alert',
                isRead: true
            },
            order: [['updatedAt', 'DESC']],
            limit: 50
        });
        res.json(history);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

const getStats = async (req, res) => {
    try {
        // Calculate total potential vs recovered
        const all = await Notification.findAll({
            where: { userId: req.user.id, type: 'sentinel_alert' }
        });
        
        const stats = {
            totalRecovered: all.filter(n => n.isRead).reduce((acc, n) => acc + (n.data?.totalPotentialRevenue || 0), 0),
            pendingRevenue: all.filter(n => !n.isRead).reduce((acc, n) => acc + (n.data?.totalPotentialRevenue || 0), 0),
            leaksDetected: all.length,
            accuracy: all.length > 0 ? (all.reduce((acc, n) => acc + (n.data?.accuracyScore || 95), 0) / all.length).toFixed(1) : 99.2 
        };
        res.json(stats);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

const createVariation = async (req, res) => {
    try {
        const { alertId } = req.body;
        const alert = await Notification.findByPk(alertId);
        if (!alert) return res.status(404).json({ error: "Alert not found" });

        const data = alert.data;
        
        // Use existing Quote Controller logic or specialized Variation logic here
        // For now, we'll return the payload structure the frontend needs to pre-fill the Invoice Builder
        
        const variationPayload = {
            projectId: data.projectId,
            projectName: data.projectName,
            clientName: data.clientName || '', // If available in notification data
            items: data.detectedItems.map(item => ({
                description: `VARIATION: ${item.description}`,
                quantity: 1,
                rate: item.estimatedCost,
                amount: item.estimatedCost,
                unit: 'ea',
                category: 'Variation'
            })),
            notes: `Generated by Sentinel based on diary entry from ${data.date}. Reason: ${data.detectedItems[0].reason}`
        };

        // Mark alert as processed
        await alert.update({ 
            isRead: true,
            data: { ...data, status: 'RECOVERED', recoveredAt: new Date() }
        });

        // Audit Logging
        await logAudit(req.user.id, 'SENTINEL_RECOVERY', 'Notification', alert.id, {
            projectId: data.projectId,
            revenueRecovered: data.totalPotentialRevenue,
            projectName: data.projectName
        });

        res.json({ variation: variationPayload, redirect: '/invoices' });

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

const getStatus = async (req, res) => {
    res.json({ 
        status: 'active', 
        engine: 'SENTINEL_CORE_V2', 
        mode: 'Military Grade Forensic Scan', 
        uplink: !!process.env.GROK_API_KEY 
    });
};

const deleteAlert = async (req, res) => {
    try {
        const alert = await Notification.findOne({
            where: { id: req.params.id, userId: req.user.id, type: 'sentinel_alert' }
        });

        if (!alert) return res.status(404).json({ error: "Alert not found" });

        const data = alert.data;
        const rows = await Notification.destroy({
            where: { id: req.params.id, userId: req.user.id }
        });

        if (rows > 0) {
            // Log the deletion
            await logAudit(req.user.id, 'SENTINEL_ALERT_PURGED', 'Notification', req.params.id, {
                projectName: data?.projectName,
                revenueAmount: data?.totalPotentialRevenue
            });
            res.json({ success: true });
        } else {
            res.status(404).json({ error: "Alert not found" });
        }
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

const clearHistory = async (req, res) => {
    try {
        const count = await Notification.count({
            where: { userId: req.user.id, type: 'sentinel_alert', isRead: true }
        });

        await Notification.destroy({
            where: { userId: req.user.id, type: 'sentinel_alert', isRead: true }
        });

        await logAudit(req.user.id, 'SENTINEL_HISTORY_CLEARED', 'System', 'Sentinel', {
            recordsCleared: count
        });

        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

module.exports = {
    runScan,
    runDeepProjectScan,
    getAlerts,
    getHistory,
    getStats,
    createVariation,
    getStatus,
    deleteAlert,
    clearHistory
};
