const sentinelService = require('../services/sentinelService');
const db = require('../models');
const { Diary, Quote, Project } = db;
// Safely load Notification model
const Notification = db.Notification || require('../models/notification')(db.sequelize, db.Sequelize.DataTypes);

const runScan = async (req, res) => {
    try {
        const { diaryId } = req.body;
        const result = await sentinelService.analyzeLeakage(diaryId, req.user.id);
        
        if (result) {
            // Create a System Notification for the "Found Money"
            await Notification.create({
                userId: req.user.id,
                type: 'sentinel_alert',
                title: '💸 Revenue Leakage Detected',
                message: `Sentinel found $${result.totalPotentialRevenue} in recoverable variations on ${result.projectName}.`,
                data: result,
                isRead: false
            });
        }

        res.json(result || { message: "No leakage detected." });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

const getAlerts = async (req, res) => {
    try {
        const alerts = await Notification.findAll({
            where: { 
                userId: req.user.id, 
                type: 'sentinel_alert',
                isRead: false 
            },
            order: [['createdAt', 'DESC']]
        });
        res.json(alerts);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

const getHistory = async (req, res) => {
    try {
        const history = await Notification.findAll({
            where: { 
                userId: req.user.id, 
                type: 'sentinel_alert',
                isRead: true
            },
            order: [['updatedAt', 'DESC']],
            limit: 50
        });
        res.json(history);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

const getStats = async (req, res) => {
    try {
        // Calculate total potential vs recovered
        const all = await Notification.findAll({
            where: { userId: req.user.id, type: 'sentinel_alert' }
        });
        
        const stats = {
            totalRecovered: all.filter(n => n.isRead).reduce((acc, n) => acc + (n.data?.totalPotentialRevenue || 0), 0),
            pendingRevenue: all.filter(n => !n.isRead).reduce((acc, n) => acc + (n.data?.totalPotentialRevenue || 0), 0),
            leaksDetected: all.length,
            accuracy: 98 // Placeholder for AI confidence metric
        };
        res.json(stats);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

const createVariation = async (req, res) => {
    try {
        const { alertId } = req.body;
        const alert = await Notification.findByPk(alertId);
        if (!alert) return res.status(404).json({ error: "Alert not found" });

        const data = alert.data;
        
        // Use existing Quote Controller logic or specialized Variation logic here
        // For now, we'll return the payload structure the frontend needs to pre-fill the Invoice Builder
        
        const variationPayload = {
            projectId: data.projectId,
            items: data.detectedItems.map(item => ({
                description: `VARIATION: ${item.description}`,
                quantity: 1,
                rate: item.estimatedCost,
                amount: item.estimatedCost,
                category: 'Variation'
            })),
            notes: `Generated by Sentinel based on diary entry from ${data.date}. Reason: ${data.detectedItems[0].reason}`
        };

        // Mark alert as processed
        await alert.update({ isRead: true });

        res.json({ variation: variationPayload, redirect: '/invoices' });

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

module.exports = {
    runScan,
    getAlerts,
    getHistory,
    getStats,
    createVariation
};
