import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateSafetyPDF = (formData, fields) => {
  const doc = new jsPDF();
  const themeColor = [220, 38, 38]; // Pro Red for Safety

  // --- HEADER ---
  doc.setFillColor(...themeColor);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text("SAFETY COMPLIANCE RECORD", 20, 25);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`ID: ${formData.id ? formData.id.slice(0, 8) : 'DRAFT'} | TYPE: ${formData.type || 'General'}`, 20, 33);

  // --- PROJECT INFO ---
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(formData.title || "Untitled Safety Form", 20, 55);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Project: ${formData.projectName || 'General Works'}`, 20, 62);
  doc.text(`Location: ${formData.locationDetails || 'Site Alpha'}`, 20, 67);
  doc.text(`Date: ${new Date(formData.createdAt || Date.now()).toLocaleDateString()}`, 140, 62);

  doc.setDrawColor(200);
  doc.line(20, 75, 190, 75);

  let currentY = 85;

  // --- RENDER FIELDS ---
  fields.forEach((field) => {
    // Check for page overflow
    if (currentY > 270) {
        doc.addPage();
        currentY = 20;
    }

    if (field.type === 'header') {
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...themeColor);
        doc.text(field.label.toUpperCase(), 20, currentY);
        currentY += 8;
    } 
    else if (field.type === 'paragraph') {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(50);
        const splitText = doc.splitTextToSize(field.value || field.label, 170);
        doc.text(splitText, 20, currentY);
        currentY += (splitText.length * 5) + 5;
    }
    else if (field.type === 'hazard') {
        doc.setDrawColor(240, 68, 68);
        doc.setFillColor(254, 242, 242);
        doc.rect(20, currentY, 170, 15, 'FD');
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(153, 27, 27);
        doc.text(`HAZARD: ${field.label}`, 25, currentY + 10);
        currentY += 20;
    }
    else if (field.type === 'risk_matrix') {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0);
        doc.text("Risk Assessment Matrix Attached", 20, currentY);
        currentY += 10;
    }
    else if (field.type === 'signature') {
        currentY += 5;
        doc.setDrawColor(200);
        doc.line(20, currentY + 15, 80, currentY + 15);
        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text(field.label || "Signature", 20, currentY + 20);
        currentY += 30;
    }
    else {
        // Standard input display
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0);
        doc.text(`${field.label}:`, 20, currentY);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(80);
        doc.text(field.value || "__________", 70, currentY);
        currentY += 8;
    }
  });

  // --- FOOTER ---
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Safety Compliance Document - Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    doc.text("Electronically Generated by MasterDiaryOS Iron Shield", 105, 295, { align: 'center' });
  }

  doc.save(`${formData.title || 'Safety_Record'}.pdf`);
  return true;
};
